window.LAUNCHES = window.LAUNCHES || [];
window.LAUNCHES.push(
{slug:"playerzero",company:"PlayerZero",date:"Mar 2026",iso:"2026-03-23",time:"4:02 PM",weekday:"Mon",
author:"Animesh Koratana",handle:"@akoratana",founder:true,
hook:"Introducing: PlayerZero — the world's first Engineering World Model that puts debugging, fixing, and testing your code on autopilot.",
full:"Introducing: PlayerZero. The world's first Engineering World Model that puts debugging, fixing, and testing your code on autopilot. We've raised $20M from Foundation Capital, @matei_zaharia (Databricks), @pbailis, @rauchg (Vercel), @zoink (Figma), @drewhouston…",
likes:5300,replies:885,platform:"X-only",format:"film",
moneyHook:true,moneyDetail:"$20M raise",
video:"https://video.twimg.com/amplify_video/2036111282349473792/vid/avc1/640x360/7bCaZEifWHk9dVn4.mp4?tag=14",
poster:"https://pbs.twimg.com/amplify_video_thumb/2036111282349473792/img/igGTAcjCioCxAbuF?format=jpg&name=small",
xUrl:"https://x.com/akoratana/status/2036111467016319074",
caseUrl:"https://www.sociallcapital.com/work/playerzero",
take:"Credibility-by-association: a devtool launch that name-drops 5 famous angels in the first 280 chars."},
{slug:"wispr-flow",company:"Wispr Flow",date:"Feb 2026",iso:"2026-02-23",time:"5:09 PM",weekday:"Mon",
author:"Tanay Kothari",handle:"@tankots",founder:true,
hook:"We offered 5 people a Porsche 911 GT3 RS if they could get @WisprFlow to make a mistake.",
full:"We offered 5 people a Porsche 911 GT3 RS if they could get @WisprFlow to make a mistake. It's the fastest and most accurate AI voice dictation app — 3x more accurate than ChatGPT, Claude, or Siri. Today, we're finally launching on Android.",
likes:10800,replies:4500,platform:"LinkedIn",format:"film",
moneyHook:false,moneyDetail:"stunt bounty (Porsche)",
video:"https://video.twimg.com/amplify_video/2025975637392207872/vid/avc1/1280x720/a9AAhGGApCxv0XDT.mp4",
poster:"https://pbs.twimg.com/amplify_video_thumb/2025975637392207872/img/eTPK-PWkdG_uOiUe?format=jpg&name=small",
xUrl:"https://x.com/tankots/status/2025981424470479008",
caseUrl:"https://www.sociallcapital.com/work/wispr-flow",
take:"Reply-bait engineering: a challenge mechanic drives 4.5K replies — 41.7% reply rate, highest in the vault."},
{slug:"poly-ai",company:"PolyAI",date:"Feb 2026",iso:"2026-02-17",time:"3:59 PM",weekday:"Tue",
author:"PolyAI",handle:"@polyaivoice",founder:false,
hook:"PolyAI has raised $200M… we handle 500M+ calls for Marriott, PG&E, Gordon Ramsay's restaurants + 3,000 more.",
full:"PolyAI has raised $200M from Nvidia, Khosla Ventures, and multiple top VCs. We're one of the fastest-growing companies in the UK, and we handle 500M+ calls for Marriott, PG&E, Gordon Ramsay's restaurants and 3,000 more real deployments…",
likes:4800,replies:1500,platform:"X-only",format:"film",
moneyHook:true,moneyDetail:"$200M raise",
video:"https://video.twimg.com/amplify_video/2023781188654022658/vid/avc1/1920x1080/4BeklZ-i4XB215Z-.mp4",
poster:"https://pbs.twimg.com/amplify_video_thumb/2023781188654022658/img/fP2-hA1kW0HMjrCc?format=jpg&name=small",
xUrl:"https://x.com/polyaivoice/status/2023789465509015972",
caseUrl:"https://www.sociallcapital.com/work/poly-ai",
take:"The lone exception: posted from the company account, not the founder — and the only UK / enterprise-proof launch."},
{slug:"airwallex",company:"Airwallex",date:"Dec 2025",iso:"2025-12-08",time:"1:03 PM",weekday:"Mon",
author:"Jack Zhang",handle:"@awxjack",founder:true,
hook:"Stripe offered to acquire us for $1.2B when we had $2M in revenue. Today: $330M at $8B, $1B ARR. The story I've never told.",
full:"Stripe offered to acquire us for $1.2 billion when we had $2M in revenue. Today, we've raised $330M at an $8B valuation and reached $1B ARR. We could've died three times. This is the story I've never told anyone before…",
likes:29700,replies:1500,platform:"LinkedIn",format:"story",
moneyHook:true,moneyDetail:"$330M / $8B / $1B ARR",
video:null,poster:null,
xUrl:"https://x.com/awxjack/status/1998015620072587516",
caseUrl:"https://www.sociallcapital.com/work/airwallex",
take:"Like-farming via rejection story: most-liked post in the vault (29.7K) but lowest reply rate (5.1%). Text-only, LinkedIn-native."},
{slug:"gamma",company:"Gamma",date:"Nov 2025",iso:"2025-11-10",time:"1:50 PM",weekday:"Mon",
author:"Grant Lee",handle:"@thisisgrantlee",founder:true,
hook:"As shared by the New York Times: Series B at $2.1B led by a16z + $100M ARR, profitably, with 50 people.",
full:"Today, as shared by The New York Times: we're announcing our Series B at a $2.1B valuation led by @sarahdingwang at @a16z, and reaching $100M ARR, profitably, with a team of just 50 people. That's $2M ARR per employee…",
likes:2800,replies:405,platform:"LinkedIn",format:"film",
moneyHook:true,moneyDetail:"$2.1B / $100M ARR",
video:"https://video.twimg.com/amplify_video/1987871318721679360/vid/avc1/1280x720/iQx_SYC06yJsdnXH.mp4",
poster:"https://pbs.twimg.com/amplify_video_thumb/1987871318721679360/img/fD4qBiilfaxlvamd?format=jpg&name=small",
xUrl:"https://x.com/thisisgrantlee/status/1987880600661889356",
caseUrl:"https://www.sociallcapital.com/work/gamma",
take:"Press-borrowed trust: the only hook that opens with NYT + a16z instead of the product."}
);
